fixed test runner

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -5,8 +5,25 @@ runner=$1
 dir=${BASH_SOURCE%/*}
 cd $dir/..
 
+failed=0
 for f in `ls ./tests/*/*py`
 do
 	echo "Running: ${runner} $f"
 	${runner} $f
+	res=$?
+
+	if [[ "$res" == "0" ]];
+	then
+		echo "OK"
+	else
+		echo "ERROR $f"
+		((failed++))
+	fi
 done
+
+if ((failed != 0))
+then
+	exit 1
+else
+	echo "All tests passed"
+fi	
